// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWwz2HU3HYyzLCu-BByDx4TolacQt2F18',
    appId: '1:432419785410:web:0be4ab24ce199b0445c95b',
    messagingSenderId: '432419785410',
    projectId: 'lecture11-cb1a1',
    authDomain: 'lecture11-cb1a1.firebaseapp.com',
    databaseURL: 'https://lecture11-cb1a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lecture11-cb1a1.appspot.com',
    measurementId: 'G-CZ443S53HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCwD-7QPNRdqmDyvr0YBGv1f9_VQyE0Ug',
    appId: '1:432419785410:android:9ee52481a7f901e245c95b',
    messagingSenderId: '432419785410',
    projectId: 'lecture11-cb1a1',
    databaseURL: 'https://lecture11-cb1a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lecture11-cb1a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_sUyUF2qeyk1RmJf-jnO3WmG385l9DEo',
    appId: '1:432419785410:ios:a9fb2a5aace11a8f45c95b',
    messagingSenderId: '432419785410',
    projectId: 'lecture11-cb1a1',
    databaseURL: 'https://lecture11-cb1a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lecture11-cb1a1.appspot.com',
    iosBundleId: 'com.example.lecture11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_sUyUF2qeyk1RmJf-jnO3WmG385l9DEo',
    appId: '1:432419785410:ios:38bec7068bf92e1d45c95b',
    messagingSenderId: '432419785410',
    projectId: 'lecture11-cb1a1',
    databaseURL: 'https://lecture11-cb1a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lecture11-cb1a1.appspot.com',
    iosBundleId: 'com.example.lecture11.RunnerTests',
  );
}
